<a href="https://colab.research.google.com/github/afrin2310/HTML-files/blob/main/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.rand(2,2)

tensor([[0.9029, 0.6462],
        [0.8117, 0.4702]])

In [ ]:
x=torch.empty(4) #1-D tensor
print(x)

tensor([3.7858e-34, 0.0000e+00, 3.6368e-34, 0.0000e+00])


In [ ]:
x=torch.empty(2,3) #2-D tensor
print(x)

tensor([[3.3704e-34, 0.0000e+00, 3.3608e-34],
        [0.0000e+00, 2.0700e-19, 7.0362e+22]])


In [ ]:
torch.empty(2,2,3) #3-D Tensor

tensor([[[2.9948e+08, 4.3624e-41, 3.6014e-34],
         [0.0000e+00, 3.4376e-34, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 3.3704e-34, 0.0000e+00]]])

In [ ]:
torch.empty(3,2,2,4) #4-D tensor

tensor([[[[2.9948e+08, 4.3624e-41, 3.3547e-34, 0.0000e+00],
          [4.4842e-44, 0.0000e+00, 1.5695e-43, 0.0000e+00]],

         [[3.4312e-34, 0.0000e+00, 0.0000e+00, 1.4013e-45],
          [3.3650e-34, 0.0000e+00, 1.8619e-13, 4.3624e-41]]],


        [[[3.3650e-34, 0.0000e+00, 1.0061e-11, 6.7016e-10],
          [5.6052e-44, 0.0000e+00, 3.5873e-43, 2.5353e+30]],

         [[1.9713e-13, 4.3624e-41, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[4.3120e-08, 1.3087e-11, 2.7045e-43, 0.0000e+00],
          [3.7871e-34, 0.0000e+00, 3.4347e-34, 0.0000e+00]],

         [[2.4421e-18, 3.1360e+27, 7.0800e+31, 3.1095e-18],
          [2.9907e+21, 1.1626e+27, 6.8664e-44, 0.0000e+00]]]])

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
x=torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
x.size()

torch.Size([2, 2])

In [ ]:
x.ndim

2

In [ ]:
x=torch.ones(3,3,dtype=torch.int)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [ ]:
torch.tensor([4.2,3.1,5,2])

tensor([4.2000, 3.1000, 5.0000, 2.0000])

In [ ]:
torch.manual_seed(42)
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [ ]:
z=x+y
print(z)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])


In [ ]:
torch.add(x,y)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [ ]:
z=x-y
print(z)

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])


In [ ]:
torch.sub(x,y)

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])

In [ ]:
torch.mul(x,y)

tensor([[1.7030, 0.0934],
        [1.5661, 0.6072]])

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.9408, 0.1332],
        [0.9346, 0.5936]])
tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])


In [ ]:
y.add_(x)

tensor([[1.8102, 0.7009],
        [1.6757, 1.0230]])

In [ ]:
z=x+y
print(z)

tensor([[2.7509, 0.8341],
        [2.6103, 1.6166]])


In [ ]:
x=torch.rand(5,3)
print(x)

tensor([[0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814]])


In [ ]:
x[:,1]

tensor([0.8860, 0.8090, 0.5547, 0.3644, 0.7890])

In [ ]:
x[:,2]

tensor([0.5832, 0.5779, 0.3423, 0.7104, 0.2814])

In [ ]:
x=torch.rand(1)
print(x)

tensor([0.7886])


In [ ]:
x.item()

0.788632333278656

In [ ]:
x=torch.rand(4,4)
print(x)
x.view(16)

tensor([[0.3278, 0.6532, 0.3958, 0.9147],
        [0.2036, 0.2018, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790]])


tensor([0.3278, 0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666,
        0.9811, 0.0874, 0.0041, 0.1088, 0.1637, 0.7025, 0.6790])

In [ ]:
x.view(2,2,4)

tensor([[[0.3278, 0.6532, 0.3958, 0.9147],
         [0.2036, 0.2018, 0.2018, 0.9497]],

        [[0.6666, 0.9811, 0.0874, 0.0041],
         [0.1088, 0.1637, 0.7025, 0.6790]]])

In [ ]:
#Convering tensor into a numpy array
a=torch.ones(6)
print(a)
print(type(a))
print("-----------")
b=a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
-----------
[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
a.add(3)

tensor([13., 13., 13., 13., 13., 13.])

In [ ]:
print(b)

[10. 10. 10. 10. 10. 10.]


In [ ]:
#Convert Numpy array to a tensor
import numpy as np
a=np.ones(5)
print(a)
print(type(a))
b=torch.from_numpy(a)
print(b)



[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
a+=2
print(a)

[3. 3. 3. 3. 3.]


In [ ]:
print(b)


tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [ ]:
#Backpropogationin pytorch
x=torch.tensor(4.,requires_grad=True)
print(x)

tensor(4., requires_grad=True)
